# Generated by Django 5.2.8 on 2025-12-28 18:10

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_order_id_alter_orderitem_id_alter_plant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('indoor', 'Indoor Plants'), ('outdoor', 'Outdoor Plants'), ('low_maintenance', 'Low Maintenance Plants'), ('air_purifying', 'Air Purifying Plants'), ('pet_friendly', 'Pet Friendly Plants'), ('flowering', 'Flowering Plants'), ('fruit', 'Fruit Plants')], default='indoor', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='plant',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
